config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

 root to: 'pages#index'

get "/categories/:id", to: "dishes#categories", as: "categories"

  devise_for :users

resources :userparams

resources :dishes do
  resources :dishcomments
    member do
    end
  end
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :dishes
end

app/models/dish.rb
class Dish < ApplicationRecord
	belongs_to :category
	belongs_to :user
	has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>", small: "50x50>" }, default_url: "/images/Default.png"
    validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
end

app/models/dishcomment.rb
class Dishcomment < ApplicationRecord
	belongs_to :user
	belongs_to :dish
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :userparam, dependent: :destroy
  has_many :dishes
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", small: "50x50>" }, default_url: "/images/avatar.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_many :doshcomments

  
end

app/models/userparam.rb
class Userparam < ApplicationRecord

	belongs_to :user


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :devise_sign_up_params, if: :devise_controller?
  protect_from_forgery with: :exception


 def devise_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys:[:avatar])
  end
 
end

app/controllers/dishcomments_controller.rb
class DishcommentsController < ApplicationController

	def create
    params[:dishcomment][:dish_id] = params[:dish_id]
    params[:dishcomment][:user_id] = current_user.id
    @dishcomment = Dishcomment.create(dishcomments_params)
    if @dishcomment.save
      redirect_to dish_path(params[:dish_id])
    else
      @dishcomment.errors.full_messages.each do |msg|
        @msg = msg
    end  
      flash[:notice] = "#{@msg}"
      redirect_to dish_path(params[:dish_id])
      end
      
  end


  private
  def dishcomments_params
    params.require(:dishcomment).permit(:user_id, :dish_id, :texofcom)
  
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

	before_action :authenticate_user!
    before_action :set_dish, only:[:show, :destroy, :edit, :update]

  def index
  end

  def new
    @dish = Dish.new
  end

  def create
    if current_user.role == "Editor"
      params[:dish][:category_id] = params[:category_id]
      @dish = current_user.dishes.build(dish_params)
    if @dish.save
      redirect_to root_path
    else
      render 'new'
    end
  end
end


 def show
    @comments = Dishcomment.where(dish_id: @dish.id)
  end

  def category
    pp @dishes=Dish.where(category_id: params[:id])
  end



  private

  
  def dish_params
    params.require(:dish).permit(:name, :description, :receipt, :price, :user_id, :category_id, :logo)
  end

  def set_dish
    @dish=Dish.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
	@user = User.all
	@dishes = Dish.all 
  end
end

app/controllers/userparams_controller.rb
class UserparamsController < ApplicationController
before_action :authenticate_user!
before_action :get_userparam, except: [:new, :create]


  def index
    if @userparam.nil?
      redirect_to new_userparam_path
    else
      redirect_to userparam_path(@userparam.id)
    end
  end

  def show
    @user = Userparam.find(current_user.userparam.id)
  end

  def new
    @userparam = Userparam.new
  end

  def create
    @userparam = current_user.build_userparam(userparams_params)
    if @userparam.save
      redirect_to userparam_path(@userparam.id)
    end
  end

  def edit
  end


  def update
    @userparam.update(userparams_params)
    redirect_to userparam_path(@userparam.id)
  end

private

  def userparams_params
    params.require(:userparam).permit(:user_id, :firstname, :lastname, :country, :city, :phone)
  end

  def get_userparam
    @userparam = Userparam.find_by(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishcomments_helper.rb
module DishcommentsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/userparams_helper.rb
module UserparamsHelper
end

app/views/dishes/_dish.html.erb
<div class="col-md-4">
<div class="my-container">
	

	<div align="center">	
			<%= image_tag dish.logo.url(:medium), width: 380, height: 380 %>
	</div>
<hr>
  <h3 style="text-align: center; text-decoration: none;"><%=link_to dish.name, dish_path(dish.id) %></h3>

<p><%= dish.description %></p>



</div>
</div>

app/views/dishes/_form.html.erb
<%= form_for @dish do |f| %>

<p><%= f.label :category %></p>
<%= select_tag 'category_id', options_from_collection_for_select(Category.all, 'id', 'name')%>



<div class="form-group">
   <%= f.label :logo %><br />
   <%= f.file_field :logo %>
</div>

<div class="form-group">
   <%= f.label :name %>
   <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
   <%= f.label :description %>
   <%= f.text_area :description, class: 'form-control' %>
</div>

<div class="form-group">
   <%= f.label :receipt %>
   <%= f.text_area :receipt, class: 'form-control' %>
</div>


<div class="form-group">
   <%= f.label :price %>
   <%= f.text_field :price, class: 'form-control' %>
</div>

<div class="form-group">
   <%= f.submit 'Зберегти', class: 'btn btn-primary' %>
     <%= link_to 'Назад', :back, class: 'btn btn-outline-secondary'%>
</div>

<% end %>

app/views/dishes/categories.html.erb
<div align="center">
<% @dishes.each do |dish|%>
<%= render 'dishes/dish', dish:dish %>
<%end%>
</div>

app/views/dishes/new.html.erb
<h2> Додати нову страву </h2>
<%= render 'form' %>

app/views/dishes/show.html.erb
<h1 align="center"><%= @dish.name %></h1>
	<div align="center">	
			<%= image_tag @dish.logo.url(:medium), width: 380, height: 380 %>
	</div>
	<hr>
      <div class="col-md-12" style="text-align: justify;">
        <p>Опис: <%=@dish.description %></p>
        <%= @dish.receipt%>
      </div>
      price : <%= @dish.price%>
    <hr>
      <% @comments.each do |comment|%>
      <p><%= image_tag comment.user.avatar.url(:thumb), width: 60, height: 60 %> |
  
     User: <%= comment.user.email %> </p>
    <p><%=comment.texofcom%></p>
    <p style="text-align: right;">Create at: <%= comment.created_at %></p><hr>
    <%end%>

    <div class="col-md-12">
              
            
    </div>
    <%= form_for :dishcomment, url: dish_dishcomments_path(@dish.id) do |dish| %>

    <% if flash[:notice] %>
      <div class="notice"> <%= flash[:notice] %> </div>
    <% end %>
    <div align="center">
    <p><%= dish.label "Залишити відгук" %></p>
    <%= dish.text_area :texofcom, cols: 60, rows: 5 %><br />
    <br/>
    <p><%= dish.submit "Send", class: "btn btn-primary active"%></p><br/>
    </div>
    <%end%>
    </div>
  
  </div>

</div>

app/views/layouts/_footer.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <section style="height:80px;"></section>
    <div class="row" style="text-align:center;">
        <h2></h2>
    </div>
    <!----------- Footer ------------>
    <footer class="footer-bs">
        <div class="row">
            <div class="col-md-3 footer-brand animated fadeInLeft">
                <h2>Logo</h2>
                <p>In search of something new for your family? Here you are! We gave you the best food recipes. We have rather categories of food, you can search anything you want.</p>
                <p>Bon appetite!  </p>
            </div>
            <div class="col-md-4 footer-nav animated fadeInUp">
                <h4>Menu —</h4>
                <div class="col-md-6">
                    <ul class="pages">
                        <li><a href="#">Soups</a></li>
                        <li><a href="#">Desserts</a></li>
                        <li><a href="#">Dishes</a></li>
                        <li><a href="#">Fast Food</a></li>
                    </ul>
                </div>
                <div class="col-md-6">
                    <ul class="list">
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Contacts</a></li>
                        <li><a href="#">Terms & Condition</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2 footer-social animated fadeInDown">
                <h4>Follow Us</h4>
                <ul>
                    <li><a href="https://www.facebook.com/zsolti.nagy.583">Facebook</a></li>
                    <li><a href="https://twitter.com/login?lang=uk">Twitter</a></li>
                    <li><a href="https://www.instagram.com/">Instagram</a></li>
                </ul>
            </div>
            <div class="col-md-3 footer-ns animated fadeInRight">
                <h4>Newsletter</h4>
                <p>A rover wearing a fuzzy suit doesn’t alarm the real penguins</p>
                <p>
                    <div class="input-group">
                      <input type="text" class="form-control" placeholder="Search for...">
                      <span class="input-group-btn">
                        <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-envelope"></span></button>
                      </span>
                    </div><!-- /input-group -->
                 </p>
            </div>
        </div>
    </footer>
    

app/views/layouts/_navbar.html.erb
<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<body>

<nav class="navbar navbar-default navbar-inverse" role="navigation">
  <div class="container-fluid">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Main</a>
    </div>

    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Weekly Top</a></li>
        <li><a href="#">Saved</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/categories/1">Desserts</a></li>
            <li><a href="/categories/2">Dishes</a></li>
            <li><a href="/categories/3">Fast Food</a></li>
            <li><a href="/categories/4">Else...</a></li>
          </ul>
        </li>

      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><p class="navbar-text">Already have an account?</p></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
      <ul id="login-dp" class="dropdown-menu">
        <li>
           <div class="row">
              <div class="col-md-12">
                Login via
                <div class="social-buttons">
                  <a href="https://www.facebook.com" class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>
                  <a href="https://twitter.com" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
                </div>
                  <% if current_user.nil? %>
                    <%= link_to user_session_path do %>
                    <div class="form-group">
                       <button type="submit" class="btn btn-primary btn-block">Sign in</button>
                    </div>
                    <%end%>
                    <% else %>
                    <%= link_to destroy_user_session_path, method: :delete do %>
                    <button type="submit" class="btn btn-primary btn-block">Logout</button>
                    <%end%>
                <% end %>
                <br>
           </div>
        </li>
      </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectKaja</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navbar'%>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </body>

</html>

app/views/pages/index.html.erb
<h1 align = "center">Kaja - Food for everything!</h1>

<% @dishes.each do |dish| %>
    <%= render 'dishes/dish', dish:dish %>
<%end%>

app/views/userparams/_form.html.erb
  <div class="form-group">
   <%= f.text_field :firstname, placeholder: "First name", autofocus: true %>    
  </div>
  
  <div class="form-group">
   <%= f.text_field :lastname, placeholder: "Last name" %>    
  </div>
  
  <div class="form-group">
   <%= f.text_field :country, placeholder: "Country" %>    
  </div>
  
  <div class="form-group">
   <%= f.text_field :city, placeholder: "City" %>    
  </div>
  
  <div class="form-group">
   <%= f.text_field :phone, placeholder: "Phone number" %>    
  </div>
  
  <div class="form-group text-center m-t-30">
    <%= f.submit "Save", class: "btn btn-info" %>
  </div>

app/views/userparams/edit.html.erb
<%= form_for @userparam, validate: true, url: userparam_path(@userparam.id), method: :patch do |f| %>

<%= render 'form', f: f %>
  
<% end %>

app/views/userparams/new.html.erb
<%= form_for @userparam, url: userparams_path, validate: true do |f| %>

<%= render 'form', f: f %>
 
<% end %>

app/views/userparams/show.html.erb
<h1><%= @user.firstname %> Profile</h1>

Firstname: <%= @user.firstname %><br />
Lastname: <%= @user.lastname %><br />
Country: <%= @user.country %><br />
City: <%= @user.city %><br />
Phone: <%= @user.phone %><br />

<%= link_to "Edit Profile", edit_userparam_path %>


</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>